### PR TITLE
Modularize stuff. Sorta.

### PR DESCRIPTION
**Pull request by anthony-dandrea**
WIP for sure. This is broken but figured I'd put it up incase anyone wanted to pull take a gander.
- Mock files are split out into two different json files in `mocks/`
- `api/` contains the parsing for both brewdb (acting weird currently) and untd (not done)

Also, struggling to set breakpoints in node. I feel mildly rere.

### CODE REVIEW

**Comment by Shiggiddie** [comment]
This may help for setting traces: http://stackoverflow.com/questions/12184404/javascript-interactive-debugging-equivalent-of-pythons-pdb-set-trace

**Comment by anthony-dandrea** [comment]
@Shiggiddie That's unfortunately just for the FE. I found node has a "debugger;" on the BE - http://nodejs.org/api/debugger.html but I haven't been able to make it do what I want =-[

**Comment by anthony-dandrea** [comment]
Now working after Sean helped me fix the node module export. Going to merge unless any objections.

**Comment by DLavin23** [comment]
Go for it

—

**Pull request merged**
